"""initial schema

Revision ID: a5bfbc4fbd87
Revises: 
Create Date: 2026-07-14 19:03:16.140943
"""
from alembic import op
import sqlalchemy as sa
import app.db.base


revision = 'a5bfbc4fbd87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('location_type', sa.String(length=30), nullable=False),
    sa.Column('country', sa.String(length=60), nullable=False),
    sa.Column('dzongkhag', sa.String(length=60), nullable=False),
    sa.Column('gewog', sa.String(length=60), nullable=True),
    sa.Column('village', sa.String(length=120), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('landmark', sa.String(length=200), nullable=True),
    sa.Column('latitude', app.db.base.SafeNumeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', app.db.base.SafeNumeric(precision=9, scale=6), nullable=True),
    sa.Column('road_access_notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_dzongkhag'), 'locations', ['dzongkhag'], unique=False)
    op.create_index(op.f('ix_locations_gewog'), 'locations', ['gewog'], unique=False)
    op.create_table('products',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('local_name', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('default_unit', sa.String(length=12), nullable=False),
    sa.Column('storage_category', sa.String(length=20), nullable=False),
    sa.Column('shelf_life_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('preferred_language', sa.String(length=5), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_table('buyer_organizations',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('organization_type', sa.String(length=30), nullable=False),
    sa.Column('registration_reference', sa.String(length=80), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('billing_contact', sa.String(length=200), nullable=True),
    sa.Column('delivery_contact', sa.String(length=200), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_buyer_organizations_owner_user_id'), 'buyer_organizations', ['owner_user_id'], unique=False)
    op.create_table('disputes',
    sa.Column('raised_by', sa.Uuid(), nullable=False),
    sa.Column('related_entity_type', sa.String(length=40), nullable=False),
    sa.Column('related_entity_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['raised_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disputes_raised_by'), 'disputes', ['raised_by'], unique=False)
    op.create_index(op.f('ix_disputes_related_entity_id'), 'disputes', ['related_entity_id'], unique=False)
    op.create_index(op.f('ix_disputes_status'), 'disputes', ['status'], unique=False)
    op.create_table('farmer_groups',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('registration_reference', sa.String(length=80), nullable=True),
    sa.Column('dzongkhag', sa.String(length=60), nullable=False),
    sa.Column('gewog', sa.String(length=60), nullable=True),
    sa.Column('coordinator_user_id', sa.Uuid(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('default_collection_point_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['coordinator_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['default_collection_point_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_farmer_groups_coordinator_user_id'), 'farmer_groups', ['coordinator_user_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('sms_enabled', sa.Boolean(), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=12), nullable=False),
    sa.Column('template_key', sa.String(length=60), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_template_key'), 'notifications', ['template_key'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('product_varieties',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_varieties_product_id'), 'product_varieties', ['product_id'], unique=False)
    op.create_table('quality_grades',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_grades_product_id'), 'quality_grades', ['product_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('transport_providers',
    sa.Column('organization_name', sa.String(length=160), nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('registration_reference', sa.String(length=80), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('service_dzongkhags', sa.JSON(), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_name')
    )
    op.create_index(op.f('ix_transport_providers_owner_user_id'), 'transport_providers', ['owner_user_id'], unique=False)
    op.create_table('buyer_orders',
    sa.Column('buyer_organization_id', sa.Uuid(), nullable=False),
    sa.Column('delivery_location_id', sa.Uuid(), nullable=False),
    sa.Column('required_delivery_date', sa.Date(), nullable=False),
    sa.Column('order_status', sa.String(length=30), nullable=False),
    sa.Column('payment_terms', sa.String(length=120), nullable=True),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['buyer_organization_id'], ['buyer_organizations.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['delivery_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_orders_buyer_organization_id'), 'buyer_orders', ['buyer_organization_id'], unique=False)
    op.create_index(op.f('ix_buyer_orders_order_status'), 'buyer_orders', ['order_status'], unique=False)
    op.create_table('farmer_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('farmer_registration_reference', sa.String(length=80), nullable=True),
    sa.Column('farmer_group_id', sa.Uuid(), nullable=True),
    sa.Column('membership_status', sa.String(length=20), nullable=False),
    sa.Column('primary_phone', sa.String(length=32), nullable=True),
    sa.Column('preferred_contact_method', sa.String(length=12), nullable=False),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farmer_group_id'], ['farmer_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmer_profiles_farmer_group_id'), 'farmer_profiles', ['farmer_group_id'], unique=False)
    op.create_index(op.f('ix_farmer_profiles_user_id'), 'farmer_profiles', ['user_id'], unique=True)
    op.create_table('vehicles',
    sa.Column('transport_provider_id', sa.Uuid(), nullable=False),
    sa.Column('registration_number', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type', sa.String(length=30), nullable=False),
    sa.Column('capacity_kg', app.db.base.SafeNumeric(precision=10, scale=2), nullable=False),
    sa.Column('capacity_volume_m3', app.db.base.SafeNumeric(precision=8, scale=2), nullable=True),
    sa.Column('has_refrigeration', sa.Boolean(), nullable=False),
    sa.Column('supported_product_categories', sa.JSON(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('current_location_id', sa.Uuid(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['transport_provider_id'], ['transport_providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_index(op.f('ix_vehicles_transport_provider_id'), 'vehicles', ['transport_provider_id'], unique=False)
    op.create_table('buyer_order_items',
    sa.Column('buyer_order_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('variety_id', sa.Uuid(), nullable=True),
    sa.Column('required_quantity', app.db.base.SafeNumeric(precision=12, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=12), nullable=False),
    sa.Column('minimum_grade_id', sa.Uuid(), nullable=True),
    sa.Column('offered_unit_price', app.db.base.SafeNumeric(precision=10, scale=2), nullable=False),
    sa.Column('maximum_unit_price', app.db.base.SafeNumeric(precision=10, scale=2), nullable=True),
    sa.Column('packaging_requirement', sa.String(length=120), nullable=True),
    sa.Column('accepted_quantity', app.db.base.SafeNumeric(precision=12, scale=2), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_order_id'], ['buyer_orders.id'], ),
    sa.ForeignKeyConstraint(['minimum_grade_id'], ['quality_grades.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['variety_id'], ['product_varieties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_order_items_buyer_order_id'), 'buyer_order_items', ['buyer_order_id'], unique=False)
    op.create_index(op.f('ix_buyer_order_items_product_id'), 'buyer_order_items', ['product_id'], unique=False)
    op.create_table('farms',
    sa.Column('farmer_id', sa.Uuid(), nullable=False),
    sa.Column('farm_name', sa.String(length=120), nullable=False),
    sa.Column('dzongkhag', sa.String(length=60), nullable=False),
    sa.Column('gewog', sa.String(length=60), nullable=True),
    sa.Column('village', sa.String(length=120), nullable=True),
    sa.Column('latitude', app.db.base.SafeNumeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', app.db.base.SafeNumeric(precision=9, scale=6), nullable=True),
    sa.Column('road_access_notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farms_farmer_id'), 'farms', ['farmer_id'], unique=False)
    op.create_table('harvest_listings',
    sa.Column('farmer_id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('variety_id', sa.Uuid(), nullable=True),
    sa.Column('forecast_quantity', app.db.base.SafeNumeric(precision=12, scale=2), nullable=False),
    sa.Column('confirmed_quantity', app.db.base.SafeNumeric(precision=12, scale=2), nullable=True),
    sa.Column('available_quantity', app.db.base.SafeNumeric(precision=12, scale=2), nullable=False),
    sa.Column('collected_quantity', app.db.base.SafeNumeric(precision=12, scale=2), nullable=True),
    sa.Column('accepted_quantity', app.db.base.SafeNumeric(precision=12, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=12), nullable=False),
    sa.Column('harvest_start_date', sa.Date(), nullable=False),
    sa.Column('harvest_end_date', sa.Date(), nullable=False),
    sa.Column('minimum_unit_price', app.db.base.SafeNumeric(precision=10, scale=2), nullable=False),
    sa.Column('expected_grade_id', sa.Uuid(), nullable=True),
    sa.Column('packaging_type', sa.String(length=60), nullable=True),
    sa.Column('confidence_level', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('verified_by', sa.Uuid(), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['expected_grade_id'], ['quality_grades.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer_profiles.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['variety_id'], ['product_varieties.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_harvest_listings_farm_id'), 'harvest_listings', ['farm_id'], unique=False)
    op.create_index(op.f('ix_harvest_listings_farmer_id'), 'harvest_listings', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_harvest_listings_product_id'), 'harvest_listings', ['product_id'], unique=False)
    op.create_index(op.f('ix_harvest_listings_status'), 'harvest_listings', ['status'], unique=False)
    op.create_table('match_proposals',
    sa.Column('buyer_order_item_id', sa.Uuid(), nullable=False),
    sa.Column('proposed_quantity', app.db.base.SafeNumeric(precision=12, scale=2), nullable=False),
    sa.Column('estimated_transport_cost', app.db.base.SafeNumeric(precision=12, scale=2), nullable=True),
    sa.Column('estimated_delivery_time_hours', app.db.base.SafeNumeric(precision=6, scale=1), nullable=True),
    sa.Column('estimated_spoilage_risk', sa.String(length=10), nullable=True),
    sa.Column('matching_method', sa.String(length=40), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('score_factors', sa.JSON(), nullable=False),
    sa.Column('score_explanation', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['buyer_order_item_id'], ['buyer_order_items.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_proposals_buyer_order_item_id'), 'match_proposals', ['buyer_order_item_id'], unique=False)
    op.create_index(op.f('ix_match_proposals_status'), 'match_proposals', ['status'], unique=False)
    op.create_table('harvest_revisions',
    sa.Column('harvest_listing_id', sa.Uuid(), nullable=False),
    sa.Column('field', sa.String(length=40), nullable=False),
    sa.Column('old_value', sa.String(length=120), nullable=True),
    sa.Column('new_value', sa.String(length=120), nullable=True),
    sa.Column('changed_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['harvest_listing_id'], ['harvest_listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_harvest_revisions_harvest_listing_id'), 'harvest_revisions', ['harvest_listing_id'], unique=False)
    op.create_table('match_allocations',
    sa.Column('match_proposal_id', sa.Uuid(), nullable=False),
    sa.Column('harvest_listing_id', sa.Uuid(), nullable=False),
    sa.Column('allocated_quantity', app.db.base.SafeNumeric(precision=12, scale=2), nullable=False),
    sa.Column('agreed_unit_price', app.db.base.SafeNumeric(precision=10, scale=2), nullable=False),
    sa.Column('farmer_response', sa.String(length=12), nullable=False),
    sa.Column('farmer_response_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['harvest_listing_id'], ['harvest_listings.id'], ),
    sa.ForeignKeyConstraint(['match_proposal_id'], ['match_proposals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_allocations_harvest_listing_id'), 'match_allocations', ['harvest_listing_id'], unique=False)
    op.create_index(op.f('ix_match_allocations_match_proposal_id'), 'match_allocations', ['match_proposal_id'], unique=False)
    op.create_table('shipments',
    sa.Column('match_proposal_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('driver_name', sa.String(length=120), nullable=True),
    sa.Column('driver_phone', sa.String(length=32), nullable=True),
    sa.Column('planned_pickup_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_pickup_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_distance_km', app.db.base.SafeNumeric(precision=8, scale=1), nullable=True),
    sa.Column('route_estimate_method', sa.String(length=40), nullable=True),
    sa.Column('estimated_transport_cost', app.db.base.SafeNumeric(precision=12, scale=2), nullable=True),
    sa.Column('actual_transport_cost', app.db.base.SafeNumeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('incident_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_proposal_id'], ['match_proposals.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_match_proposal_id'), 'shipments', ['match_proposal_id'], unique=False)
    op.create_index(op.f('ix_shipments_status'), 'shipments', ['status'], unique=False)
    op.create_index(op.f('ix_shipments_vehicle_id'), 'shipments', ['vehicle_id'], unique=False)
    op.create_table('delivery_records',
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.Column('buyer_order_id', sa.Uuid(), nullable=False),
    sa.Column('delivered_quantity', app.db.base.SafeNumeric(precision=12, scale=2), nullable=False),
    sa.Column('accepted_quantity', app.db.base.SafeNumeric(precision=12, scale=2), nullable=False),
    sa.Column('rejected_quantity', app.db.base.SafeNumeric(precision=12, scale=2), nullable=False),
    sa.Column('arrival_condition', sa.String(length=200), nullable=True),
    sa.Column('rejection_reason', sa.String(length=300), nullable=True),
    sa.Column('buyer_confirmation', sa.Boolean(), nullable=False),
    sa.Column('transporter_confirmation', sa.Boolean(), nullable=False),
    sa.Column('proof_of_delivery_urls', sa.JSON(), nullable=False),
    sa.Column('discrepancy_flag', sa.Boolean(), nullable=False),
    sa.Column('discrepancy_note', sa.String(length=300), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_order_id'], ['buyer_orders.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_records_buyer_order_id'), 'delivery_records', ['buyer_order_id'], unique=False)
    op.create_index(op.f('ix_delivery_records_shipment_id'), 'delivery_records', ['shipment_id'], unique=False)
    op.create_table('shipment_stops',
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.Column('stop_type', sa.String(length=12), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('farmer_group_id', sa.Uuid(), nullable=True),
    sa.Column('farmer_id', sa.Uuid(), nullable=True),
    sa.Column('planned_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_quantity', app.db.base.SafeNumeric(precision=12, scale=2), nullable=True),
    sa.Column('collected_quantity', app.db.base.SafeNumeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farmer_group_id'], ['farmer_groups.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer_profiles.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_stops_shipment_id'), 'shipment_stops', ['shipment_id'], unique=False)
    op.create_table('collection_records',
    sa.Column('shipment_stop_id', sa.Uuid(), nullable=False),
    sa.Column('farmer_id', sa.Uuid(), nullable=False),
    sa.Column('harvest_listing_id', sa.Uuid(), nullable=False),
    sa.Column('expected_quantity', app.db.base.SafeNumeric(precision=12, scale=2), nullable=False),
    sa.Column('presented_quantity', app.db.base.SafeNumeric(precision=12, scale=2), nullable=False),
    sa.Column('accepted_quantity', app.db.base.SafeNumeric(precision=12, scale=2), nullable=False),
    sa.Column('rejected_quantity', app.db.base.SafeNumeric(precision=12, scale=2), nullable=False),
    sa.Column('quality_grade_id', sa.Uuid(), nullable=True),
    sa.Column('unit_price', app.db.base.SafeNumeric(precision=10, scale=2), nullable=False),
    sa.Column('gross_amount', app.db.base.SafeNumeric(precision=14, scale=2), nullable=False),
    sa.Column('transport_deduction', app.db.base.SafeNumeric(precision=12, scale=2), nullable=False),
    sa.Column('platform_fee', app.db.base.SafeNumeric(precision=12, scale=2), nullable=False),
    sa.Column('other_deduction', app.db.base.SafeNumeric(precision=12, scale=2), nullable=False),
    sa.Column('other_deduction_reason', sa.String(length=200), nullable=True),
    sa.Column('net_amount_due', app.db.base.SafeNumeric(precision=14, scale=2), nullable=False),
    sa.Column('rejection_reason', sa.String(length=300), nullable=True),
    sa.Column('farmer_confirmation', sa.Boolean(), nullable=False),
    sa.Column('coordinator_confirmation', sa.Boolean(), nullable=False),
    sa.Column('photo_urls', sa.JSON(), nullable=False),
    sa.Column('receipt_number', sa.String(length=24), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer_profiles.id'], ),
    sa.ForeignKeyConstraint(['harvest_listing_id'], ['harvest_listings.id'], ),
    sa.ForeignKeyConstraint(['quality_grade_id'], ['quality_grades.id'], ),
    sa.ForeignKeyConstraint(['shipment_stop_id'], ['shipment_stops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_records_farmer_id'), 'collection_records', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_collection_records_harvest_listing_id'), 'collection_records', ['harvest_listing_id'], unique=False)
    op.create_index(op.f('ix_collection_records_receipt_number'), 'collection_records', ['receipt_number'], unique=True)
    op.create_index(op.f('ix_collection_records_shipment_stop_id'), 'collection_records', ['shipment_stop_id'], unique=False)
    op.create_table('payment_records',
    sa.Column('payer_type', sa.String(length=30), nullable=False),
    sa.Column('payer_id', sa.Uuid(), nullable=True),
    sa.Column('recipient_type', sa.String(length=30), nullable=False),
    sa.Column('recipient_id', sa.Uuid(), nullable=True),
    sa.Column('related_order_id', sa.Uuid(), nullable=True),
    sa.Column('related_collection_id', sa.Uuid(), nullable=True),
    sa.Column('amount', app.db.base.SafeNumeric(precision=14, scale=2), nullable=False),
    sa.Column('amount_paid', app.db.base.SafeNumeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_method', sa.String(length=40), nullable=True),
    sa.Column('payment_reference', sa.String(length=120), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['related_collection_id'], ['collection_records.id'], ),
    sa.ForeignKeyConstraint(['related_order_id'], ['buyer_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_records_recipient_id'), 'payment_records', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_payment_records_related_collection_id'), 'payment_records', ['related_collection_id'], unique=False)
    op.create_index(op.f('ix_payment_records_related_order_id'), 'payment_records', ['related_order_id'], unique=False)
    op.create_index(op.f('ix_payment_records_status'), 'payment_records', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_records_status'), table_name='payment_records')
    op.drop_index(op.f('ix_payment_records_related_order_id'), table_name='payment_records')
    op.drop_index(op.f('ix_payment_records_related_collection_id'), table_name='payment_records')
    op.drop_index(op.f('ix_payment_records_recipient_id'), table_name='payment_records')
    op.drop_table('payment_records')
    op.drop_index(op.f('ix_collection_records_shipment_stop_id'), table_name='collection_records')
    op.drop_index(op.f('ix_collection_records_receipt_number'), table_name='collection_records')
    op.drop_index(op.f('ix_collection_records_harvest_listing_id'), table_name='collection_records')
    op.drop_index(op.f('ix_collection_records_farmer_id'), table_name='collection_records')
    op.drop_table('collection_records')
    op.drop_index(op.f('ix_shipment_stops_shipment_id'), table_name='shipment_stops')
    op.drop_table('shipment_stops')
    op.drop_index(op.f('ix_delivery_records_shipment_id'), table_name='delivery_records')
    op.drop_index(op.f('ix_delivery_records_buyer_order_id'), table_name='delivery_records')
    op.drop_table('delivery_records')
    op.drop_index(op.f('ix_shipments_vehicle_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_status'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_match_proposal_id'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_match_allocations_match_proposal_id'), table_name='match_allocations')
    op.drop_index(op.f('ix_match_allocations_harvest_listing_id'), table_name='match_allocations')
    op.drop_table('match_allocations')
    op.drop_index(op.f('ix_harvest_revisions_harvest_listing_id'), table_name='harvest_revisions')
    op.drop_table('harvest_revisions')
    op.drop_index(op.f('ix_match_proposals_status'), table_name='match_proposals')
    op.drop_index(op.f('ix_match_proposals_buyer_order_item_id'), table_name='match_proposals')
    op.drop_table('match_proposals')
    op.drop_index(op.f('ix_harvest_listings_status'), table_name='harvest_listings')
    op.drop_index(op.f('ix_harvest_listings_product_id'), table_name='harvest_listings')
    op.drop_index(op.f('ix_harvest_listings_farmer_id'), table_name='harvest_listings')
    op.drop_index(op.f('ix_harvest_listings_farm_id'), table_name='harvest_listings')
    op.drop_table('harvest_listings')
    op.drop_index(op.f('ix_farms_farmer_id'), table_name='farms')
    op.drop_table('farms')
    op.drop_index(op.f('ix_buyer_order_items_product_id'), table_name='buyer_order_items')
    op.drop_index(op.f('ix_buyer_order_items_buyer_order_id'), table_name='buyer_order_items')
    op.drop_table('buyer_order_items')
    op.drop_index(op.f('ix_vehicles_transport_provider_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_farmer_profiles_user_id'), table_name='farmer_profiles')
    op.drop_index(op.f('ix_farmer_profiles_farmer_group_id'), table_name='farmer_profiles')
    op.drop_table('farmer_profiles')
    op.drop_index(op.f('ix_buyer_orders_order_status'), table_name='buyer_orders')
    op.drop_index(op.f('ix_buyer_orders_buyer_organization_id'), table_name='buyer_orders')
    op.drop_table('buyer_orders')
    op.drop_index(op.f('ix_transport_providers_owner_user_id'), table_name='transport_providers')
    op.drop_table('transport_providers')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_quality_grades_product_id'), table_name='quality_grades')
    op.drop_table('quality_grades')
    op.drop_index(op.f('ix_product_varieties_product_id'), table_name='product_varieties')
    op.drop_table('product_varieties')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_template_key'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_farmer_groups_coordinator_user_id'), table_name='farmer_groups')
    op.drop_table('farmer_groups')
    op.drop_index(op.f('ix_disputes_status'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_related_entity_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_raised_by'), table_name='disputes')
    op.drop_table('disputes')
    op.drop_index(op.f('ix_buyer_organizations_owner_user_id'), table_name='buyer_organizations')
    op.drop_table('buyer_organizations')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('products')
    op.drop_index(op.f('ix_locations_gewog'), table_name='locations')
    op.drop_index(op.f('ix_locations_dzongkhag'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
